# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: my-pipeline

variables:
  number: First

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:

- stage: $(number) stage
  jobs:
  - job:
    - script: echo $(number) stage

- stage: Second stage
  jobs:
  - job:
    - bash: echo "Second stage"