# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: my-pipeline

variables:
  number: First

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
  - repository: templates
    type: github
    endpoint: MyGitHubService
    name: NRadojevic/azure-pipeline-templates

stages:

- stage: Checkout_repositories
  displayName: Checkout repositories
  jobs:
  - job: Checkout_repos
    displayName: Checkout repositories
    steps:
    - checkout: self
    - checkout: templates
    - bash: ls -la
    - bash: ls -la
      workingDirectory: azure-pipeline-templates
    - template: test-echo.yml@templates

#- stage: Second_stage
#  dependsOn: Checkout_repositories
#  jobs:
#   - job: Second
#    steps:
#    - template: azure-pipeline-templates/test-echo.yml